import express from "express";
import common from "../services/commonService/configServices.js";
import {middleware} from "../middlewares/middleware.js";
let router = express.Router();
router.get('/threads/:thread_id/:bridge_id', middleware, common.getThreads);
router.get('/userfeedbackcount/:bridge_id',middleware,common.userFeedbackCount);
router.get('/history/:bridge_id', middleware, common.getMessageHistory);
router.get('/history/sub-thread/:thread_id', middleware, common.getAllSubThreadsController);
router.delete('/deletebridges/:bridge_id', middleware, common.deleteBridges);
router.get('/systemprompt/gethistory/:bridge_id/:timestamp', middleware, common.getSystemPromptHistory);
router.post('/getFineTuneData/:bridge_id', middleware, common.FineTuneData);
router.put('/gethistory/:bridge_id', middleware, common.updateThreadMessage);
router.put('/bridge-status/:bridge_id', middleware, common.bridgeArchive);
router.get('/getuserupdates/:version_id', middleware, common.getAllUserUpdates);
export default router;
