import express from "express";
import common from "../services/commonService/common.js";
import middleware from "../../middlewares/middleware.js"; 
// const completion=require('../services/commonService/completion');
let router = express.Router();
router.post('/chat/completion', middleware, common.prochat);
router.post('/playground/chat/completion/:bridge_id', middleware, common.getchat);
router.post('/completion', middleware, common.proCompletion);
router.post('/playground/completion/:bridge_id', middleware, common.getCompletion);
router.post('/embeddings', middleware, common.proEmbeddings);
router.post('/playground/embeddings/:bridge_id', middleware, common.getEmbeddings);
export default router;